name: Pull Request

on: pull_request

permissions:
  contents: write

jobs:
  Client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4      
        with:
            fetch-depth: 0  
            ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-go@v5

      - name: Install Dependencies
        run: |
            cd binGO.client
            go mod tidy

      - name: Build
        run: |
            cd binGO.client
            go build

      - name: Test
        run: |
            cd binGO.client
            go test

      - name: Format
        run: |
            cd binGO.client
            go fmt

      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9
        
  Server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
        with:
            fetch-depth: 0  
            ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-go@v5

      - name: Install Dependencies
        run: |
            cd binGO.server
            go mod tidy

      - name: Build
        run: |
            cd binGO.server
            go build

      - name: Test
        run: |
            cd binGO.server
            go test

      - name: Format
        run: |
            cd binGO.server
            go fmt

      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9

  AutoApproveOnSuccess:
    runs-on: ubuntu-latest
    needs: [Client, Server]
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Approve pull request 
          if: ${{ success() }}
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
              gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}